spring.application.name=gatekeeper-web

# WICHTIG: Der Port muss dynamisch sein (Cloud gibt den Port vor)
server.port=${PORT:8080}

# Datenbank Verbindung (Wir nutzen Umgebungsvariablen)
# Wenn DB_URL nicht gesetzt ist (auf deinem PC), nehmen wir localhost (hinter dem Doppelpunkt)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gatekeeper_db}
spring.datasource.username=${DB_USER:devuser}
spring.datasource.password=${DB_PASSWORD:geheim}

# Zeige SQL nur, wenn wir es wollen
spring.jpa.show-sql=true

# Hibernate Konfiguration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Admin Login Konfiguration
# Online nimmt er ADMIN_USER, lokal 'paco'
admin.username=${ADMIN_USER:paco}

# Online nimmt er ADMIN_PASSWORD, lokal 'geheim'
admin.password=${ADMIN_PASSWORD:geheim}