spring.application.name=gatekeeper-web

# Datenbank Verbindung
spring.datasource.url=jdbc:postgresql://localhost:5432/gatekeeper_db
spring.datasource.username=devuser

spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true

# Hibernate Konfiguration (Sorgt dafür, dass Java und DB synchron bleiben)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect